name: app_dev_project_medilink_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  youtube_player_flutter: ^8.1.2
  url_launcher: ^6.2.2
  google_maps_flutter: ^2.0.12
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  provider: ^6.1.1
  firebase_ui_auth: ^1.11.0
  google_sign_in:
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  hooks_riverpod: ^2.4.9
  golden_toolkit: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/google.png
    - assets/facebook.png
    - assets/facebook1.png
    - assets/facebook2.png
    - assets/hospital.jpg
    - assets/doctor.jpg
    - assets/medicine.jpg
    - assets/firstaid.jpg
    - assets/ambulance.jpg
    - assets/bloodbank.jpg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
