// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR-F1s84meq9ZX1JYu5GJX2AE7wzwhCmM',
    appId: '1:594676834672:web:38e8cc2efcd28dd67dafb5',
    messagingSenderId: '594676834672',
    projectId: 'medilink-f3d12',
    authDomain: 'medilink-f3d12.firebaseapp.com',
    storageBucket: 'medilink-f3d12.appspot.com',
    measurementId: 'G-ZP45HG6G75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlpVMh1u066NdzPGhbbcliy6hSZvZ8yO8',
    appId: '1:594676834672:android:c515fac074b2aa2e7dafb5',
    messagingSenderId: '594676834672',
    projectId: 'medilink-f3d12',
    storageBucket: 'medilink-f3d12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0pEstETotZP0HepKkhbz893s9fm_jlTQ',
    appId: '1:594676834672:ios:0458c7804c6bc2107dafb5',
    messagingSenderId: '594676834672',
    projectId: 'medilink-f3d12',
    storageBucket: 'medilink-f3d12.appspot.com',
    iosBundleId: 'com.example.appDevProjectMedilinkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0pEstETotZP0HepKkhbz893s9fm_jlTQ',
    appId: '1:594676834672:ios:e71aea6b5f8371917dafb5',
    messagingSenderId: '594676834672',
    projectId: 'medilink-f3d12',
    storageBucket: 'medilink-f3d12.appspot.com',
    iosBundleId: 'com.example.appDevProjectMedilinkApp.RunnerTests',
  );
}
